name: Periodic health check

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v5
        with:
          url: https://fs-pokedex-z9hg.onrender.com/