name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  deploy:
    needs: [build_and_test]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' ; '), '#skip')}}
    uses: ./.github/workflows/deploy.yml
    secrets:
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_releases:
    needs: [deploy]
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' ; '), '#skip')}}
    permissions:
      contents: write
    uses: ./.github/workflows/tag_releases.yml

  notification_success:
    needs: [build_and_test, deploy, tag_releases]
    if: success()
    uses: ./.github/workflows/notify.yml
    with:
      title: 'Deployment Successful!'
      color: 'success'
      description: |
        A new version `${{ github.event.release.tag_name }}` has been deployed to Render.

        Repository: ${{ github.repository }}
        Branch: ${{ github.ref_name }}
        Commit: ${{ github.sha }}
        Author: ${{ github.actor }}

        Workflow Run:
        ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  notification-failure:
    needs: [build_and_test, deploy]
    if: failure()
    uses: ./.github/workflows/notify.yml
    with:
      title: 'Deployment Pipeline Failed'
      color: 'failure'
      description: |
        The deployment pipeline failed.

        Repository: ${{ github.repository }}
        Commit: ${{ github.sha }}
        Triggered by: ${{ github.actor }}

        Workflow:
        ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}


